# Generated by Django 5.2.11 on 2026-02-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
