# Generated by Django 5.2.11 on 2026-02-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar_url',
            new_name='avatar_image',
        ),
    ]
