# Generated by Django 5.2.11 on 2026-02-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_avatar_url_profile_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_avatar_processing',
            field=models.BooleanField(default=False),
        ),
    ]
