# Generated by Django 5.2.11 on 2026-03-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_avatar_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
