# Generated by Django 5.2.11 on 2026-02-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('cloud', 'Cloud'), ('mobile', 'Mobile'), ('tools', 'Tools')], max_length=50),
        ),
    ]
