# Generated by Django 5.2.11 on 2026-03-01 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_skill_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='merge_min_level',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='skill',
            name='merge_sources',
            field=models.ManyToManyField(blank=True, related_name='merge_results', to='core.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_level', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expected_end', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_awarded', models.PositiveSmallIntegerField()),
                ('confidence', models.FloatField()),
                ('reasoning', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('rubric_scores', models.JSONField(default=dict)),
                ('ai_raw_response', models.JSONField(default=dict)),
                ('ai_assisted_flag', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.evaluationsession')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_level', models.PositiveSmallIntegerField()),
                ('scenario', models.TextField()),
                ('task', models.TextField()),
                ('time_limit_seconds', models.PositiveIntegerField(default=480)),
                ('difficulty_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.skill')),
            ],
        ),
        migrations.CreateModel(
            name='RubricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('level_gate', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_items', to='core.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
