# Generated by Django 5.2.11 on 2026-03-09 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_skill_icon_class_skill_description_skill_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(default='Software Engineering', help_text='e.g., Fintech, Web3, Cybersec', max_length=100)),
                ('minimum_level_to_join', models.PositiveIntegerField(default=1, help_text='Min player level required to apply/join')),
                ('guild_xp', models.PositiveIntegerField(default=0, help_text='Total XP earned by members for the guild')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='guild_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_guilds', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='guilds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xp_reward', models.PositiveIntegerField(default=500, help_text='Bonus XP for landing this role')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='guilds.guild')),
            ],
        ),
        migrations.CreateModel(
            name='QuestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_level', models.PositiveIntegerField(default=1)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='guilds.quest')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
        ),
    ]
