# Generated by Django 5.2.11 on 2026-03-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Grants the 'Verified' badge to trusted recruiters."),
        ),
    ]
