# Generated by Django 5.2.11 on 2026-03-11 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_guild_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'In Progress'), ('submitted', 'Under Review'), ('approved', 'Approved & Rewarded'), ('rejected', 'Rejected')], default='accepted', max_length=20)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='guilds.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('quest', 'user')},
            },
        ),
    ]
